### ISSUE TITLE
Just a doubt

### ISSUE THREAD

**Issue by KiranPaulAlex** [TMSTweaks/ASUS-Zephyrus-M15-Hackintosh#2]
Hi Im kiran and i am going to purchase this laptop and i wish to hackintosh it. 
 did u have any issues with it . 
Just to know. how is the overall experience. what about the wifi ? Expecting immediate reply

**Comment by TMSTweaks** [comment]
Sorry for the delay, I just finished up my university classes. The overall experience is really good once you start ironing out some of the bugs. I will be updating the guide in a couple of days, but as of right now I have absolutely no issues. The wifi works great even though it is a little slower than Windows. I fixed the screen flickering as well. All of these changes and how to update to macOS Big Sur will be in the updated version of the guide coming in a couple of days.
