### ISSUE TITLE
HDMI or DP out

### ISSUE THREAD

**Issue by koluris** [TMSTweaks/ASUS-Zephyrus-M15-Hackintosh#3]
Thanks for the useful guide, I am planning on purchasing this laptop for this purpose. But, one big question remains... were you able to output to a monitor or TV in macOS by utilising either the HDMI or the DP port, or are both of these hard-wired on the disabled dedicated graphics card?

**Comment by TMSTweaks** [comment]
I am currently unable to get display out from the HDMI while in macOS. To me, this feature isn't that important so I didn't look into how to fix it. I'm sure there is some way to fix this but it probably requires some research of your own.
